build: build-lang
	npm run build

build-lang:
	npm run extract-intl

setup:
	npm run setup

start:
	npm run start

test:
	npm test

test-watch:
	npm run test:watch

generate:
	npm run generate $(GENERATOR)

lint:
	npm run lint